name: Flutter Build APK

# Trigger the workflow when pushing to the `main` branch
on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # You can change this to any version you prefer

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
